language: python
matrix:
  include:
    - python: 3.7
      sudo: yes
      dist: xenial
# command to install dependencies
install:
  - pip install torch==1.7.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install -e .[tests]
# command to run tests
script:
  - pytest tests/
notifications:
  email:
    on_success: never
    on_failure: always
